name: quark_web
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  visibility_detector: ^0.4.0+2
  carousel_slider: ^5.0.0
  firebase_core: ^3.8.1
  firebase_analytics: ^11.3.6
  cloud_firestore: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  icons_launcher: ^3.0.0

icons_launcher:
  image_path: 'assets/isotipo.png'
  platforms:
    web:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/isotipo.png
    - assets/isologo.png
    - assets/office.png
    - assets/mobile_app.png
    - assets/web_development.png
    - assets/software_development.png
    - assets/janodanihugoproyect.png
    - assets/favicon.jpeg
    - assets/awsLogo.png
    - assets/dartLogo.png
    - assets/firebaseLogo.png
    - assets/flutterLogo.png
    - assets/androidLogo.png
    - assets/iosLogo.png
    - assets/pythonLogo.webp
    - assets/en.png
    - assets/es.png